services:
  app-a:
    image: fabriciosveronez/app-telemetria:v1
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"  # API HTTP principal
    environment:
      - APP_NAME=app-a
      - APP_URL_DESTINO=http://app-b:8000,http://app-c:8000
      - APP_ERRORS=5
      - APP_LATENCY=100
      - OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - app-network
    depends_on:
      - otel-collector

  app-b:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "8001:8000"  # API HTTP app-b
    environment:
      - APP_NAME=app-b
      - APP_URL_DESTINO=http://app-c:8000
      - APP_ERRORS=10
      - APP_LATENCY=150
      - OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - app-network
    depends_on:
      - otel-collector      

  app-c:
    build: 
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "8002:8000"  # API HTTP app-c
    environment:
      - APP_NAME=app-c
      - APP_ERRORS=15
      - APP_LATENCY=200
      - OTLP_ENDPOINT=http://otel-collector:4318
    networks:
      - app-network
    depends_on:
      - otel-collector      

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # UI Web do Jaeger
      - "14250:14250"   # gRPC para collector
      - "14268:14268"   # HTTP direto de clientes
      - "6831:6831/udp" # Jaeger Thrift compact UDP
      - "6832:6832/udp" # Jaeger Thrift binary UDP
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - app-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # UI Web do Prometheus
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"  # API HTTP do Loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network
  
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Jaeger
          type: jaeger
          access: proxy
          orgId: 1
          url: http://jaeger:16686
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
          uid: jaeger
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
          uid: prometheus
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # UI Web do Grafana
    networks:
      - app-network    
    depends_on:
      - loki
      - jaeger
      - prometheus    

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.128.0
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"  # OTLP HTTP receiver
      - "4317:4317"  # OTLP gRPC receiver
      - "8889:8889"  # Prometheus metrics endpoint
    networks:
      - app-network
    depends_on:
      - jaeger
      - prometheus
      - loki
      - grafana

networks:
  app-network:
    driver: bridge